/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    AgoraDaoFabric: {
      address:
        "0x34231bc70dd4f46adf066b829ac715736a976da210d4773bb9ab834153a4ec3",
      abi: [
        {
          type: "impl",
          name: "AgoraDaoFabric",
          interface_name:
            "contracts::agora_dao_fabric::contract::IAgoraDaoFabric",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::agora_dao_fabric::core::structs::Dao",
          members: [
            {
              name: "dao_ID",
              type: "core::integer::u16",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "dao_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "name",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "description",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "category",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "image_URI",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "is_public",
              type: "core::bool",
            },
            {
              name: "creation_timestamp",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::agora_dao_fabric::contract::IAgoraDaoFabric",
          items: [
            {
              type: "function",
              name: "create_dao",
              inputs: [
                {
                  name: "name",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "description",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "category_ID",
                  type: "core::integer::u16",
                },
                {
                  name: "image_URI",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "is_public",
                  type: "core::bool",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "add_user",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "user_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "dao_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_all_categories",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<core::byte_array::ByteArray>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_public_daos",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<contracts::agora_dao_fabric::core::structs::Dao>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::agora_dao_fabric::core::events::DaoCreated",
          kind: "struct",
          members: [
            {
              name: "dao_ID",
              type: "core::integer::u16",
              kind: "key",
            },
            {
              name: "name",
              type: "core::byte_array::ByteArray",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao_fabric::contract::AgoraDaoFabric::Event",
          kind: "enum",
          variants: [
            {
              name: "DaoCreated",
              type: "contracts::agora_dao_fabric::core::events::DaoCreated",
              kind: "nested",
            },
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
          ],
        },
      ],
      classHash:
        "0x40db0689d2707633b4288925722f3f4da4f5da5b87e7ee916a777915a8d4f3d",
    },
  },
  sepolia: {
    AgoraDaoFabric: {
      address:
        "0x3d0860b2a0736ded4f0fa259bffa5bac7a77268de6f221bce48d873dd44dc43",
      abi: [
        {
          type: "impl",
          name: "AgoraDaoFabric",
          interface_name:
            "contracts::agora_dao_fabric::contract::IAgoraDaoFabric",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::agora_dao_fabric::core::structs::Dao",
          members: [
            {
              name: "dao_ID",
              type: "core::integer::u16",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "dao_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "name",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "description",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "category",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "image_URI",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "is_public",
              type: "core::bool",
            },
            {
              name: "creation_timestamp",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::agora_dao_fabric::contract::IAgoraDaoFabric",
          items: [
            {
              type: "function",
              name: "create_dao",
              inputs: [
                {
                  name: "name",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "description",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "category_ID",
                  type: "core::integer::u16",
                },
                {
                  name: "image_URI",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "is_public",
                  type: "core::bool",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "add_user",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "user_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "dao_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_all_categories",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<core::byte_array::ByteArray>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_public_daos",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<contracts::agora_dao_fabric::core::structs::Dao>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::agora_dao_fabric::core::events::DaoCreated",
          kind: "struct",
          members: [
            {
              name: "dao_ID",
              type: "core::integer::u16",
              kind: "key",
            },
            {
              name: "name",
              type: "core::byte_array::ByteArray",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao_fabric::contract::AgoraDaoFabric::Event",
          kind: "enum",
          variants: [
            {
              name: "DaoCreated",
              type: "contracts::agora_dao_fabric::core::events::DaoCreated",
              kind: "nested",
            },
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
          ],
        },
      ],
      classHash:
        "0x1fe8bbbb2690ca04dd84c565d5a1404df34b8203592bf3a8d09e0475d2ab61c",
    },
  },
} as const;

export default deployedContracts;
